apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-example
  namespace: operations
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
    namespace: 
  target:
    name: example-sync
  data:
  - secretKey: hola
    remoteRef:
      key: sample-secret
      property: hola