apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-namespace

resources:
  - ../../base

images:
  - name: hola-mundobase
    newName: 465344186354.dkr.ecr.us-east-1.amazonaws.com/hola-mundobase
    newTag: "1.0.0"